apiVersion: v1
kind: apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 3
  selector:
    app: mynginx-rc
  template:
    metadata:
      name: mynginx-rc
      labels:
        app: mynginx-rc
    spec:
      containers:
        - name: mynginx-container
          image: nginx
          ports:
            - containerPort: 80
