apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 4
  selector:
    app: myjavaapp
  template:
    metadata:
      name: myjavaapp
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: myjava-container
          image: sipu1996/gugujenkinsimage
          ports:
            - containerPort: 8080
